default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV.fetch("MYSQL_USERNAME") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: 127.0.0.1
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false
  timeout: 5000

development:
  <<: *default
  database: wolves_on_rails_development

test:
  <<: *default
  database: wolves_on_rails_test

production:
  <<: *default
  database: wolves_on_rails_production
